#!/usr/bin/env node
// Optional: Import catalog data from CSV/XLSX into miniprogram/data/catalog.js
import fs from 'fs';
import path from 'path';
import { parse } from 'csv-parse/sync';
import xlsx from 'xlsx';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { ASSET_BASE_URL } = require('./config.cjs');

function assetUrl(category, filename){
  const cat = String(category||'').replace(/^\/+|\/+$/g,'');
  const fn = String(filename||'').replace(/^\/+/, '');
  if (ASSET_BASE_URL) {
    const base = ASSET_BASE_URL.replace(/\/$/, '');
    return `${base}/prod-images/${cat}/${fn}`;
  }
  return `/assets/${cat}/${fn}`;
}

const repoRoot = process.cwd();
const inputDir = path.join(repoRoot, 'import');
const imagesDir = path.join(inputDir, 'images');
const dataFileCSV = path.join(inputDir, 'products.csv');
const dataFileXLSX = path.join(inputDir, 'products.xlsx');
const outJs = path.join(repoRoot, 'miniprogram', 'data', 'catalog.js');
const assetsDir = path.join(repoRoot, 'miniprogram', 'assets');

function ensureDir(p) { if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true }); }

function loadRows() {
  if (fs.existsSync(dataFileXLSX)) {
    const wb = xlsx.readFile(dataFileXLSX);
    const ws = wb.Sheets[wb.SheetNames[0]];
    return xlsx.utils.sheet_to_json(ws, { defval: '' });
  }
  if (fs.existsSync(dataFileCSV)) {
    const content = fs.readFileSync(dataFileCSV, 'utf-8');
    return parse(content, { columns: true, skip_empty_lines: true });
  }
  console.error('No products.xlsx or products.csv found under ./import');
  process.exit(1);
}

function normalize(rows) {
  // Expect columns: 类型,名字,简单描述,照片,价格
  const catMap = new Map();
  const categories = [];
  const products = [];
  rows.forEach((r, idx) => {
    const catName = (r['类型'] || r['category'] || '未分类').trim();
    const name = (r['名字'] || r['name'] || `商品${idx+1}`).trim();
    const brief = (r['简单描述'] || r['brief'] || '').trim();
    const photo = (r['照片'] || r['cover'] || '').trim();
    const price = Number(r['价格'] || r['price'] || 0);
    let catId = catMap.get(catName);
    if (!catId) {
      catId = `cat_${categories.length+1}`;
      catMap.set(catName, catId);
      categories.push({ id: catId, name: catName });
    }
    // copy image if exists
    let cover = '/assets/p1.jpg';
    if (photo) {
      const src = path.isAbsolute(photo) ? photo : path.join(imagesDir, photo);
      if (fs.existsSync(src)) {
        ensureDir(assetsDir);
        const dst = path.join(assetsDir, path.basename(src));
        fs.copyFileSync(src, dst);
        cover = assetUrl('', path.basename(src));
      }
    }
    products.push({ id: `p_${idx+1}`, categoryId: catId, name, price, brief, cover });
  });
  return { categories, products };
}

function writeJs({ categories, products }) {
  const header = '// Generated by scripts/import-catalog.mjs\n';
  const body = `const categories = ${JSON.stringify(categories, null, 2)};\n\nconst products = ${JSON.stringify(products, null, 2)};\n\nmodule.exports = { categories, products };\n`;
  ensureDir(path.dirname(outJs));
  fs.writeFileSync(outJs, header + body);
}

ensureDir(assetsDir);
const rows = loadRows();
const data = normalize(rows);
writeJs(data);
console.log('Catalog generated at', path.relative(repoRoot, outJs));
